name: Build
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
  ktlint:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run ktlint check (codestyle)
        run: ./gradlew ktlintcheck
  detekt:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Detekt check (codestyle)
        run: ./gradlew detekt
  unit_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Unit tests
        run: ./gradlew test